version: "3.9"
services:
  backend:
    build: .
    ports:
      - "80:5001"
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4080:4080"
